<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Platforms>AnyCPU</Platforms>
        <LangVersion>9</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\HardwareInformation\HardwareInformation.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Reinforced.Typings" Version="1.6.7" />
    </ItemGroup>

</Project>
