name: .NET Core CI

on: push

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '3.0.100-preview8-013656' ]
    name: Dotnet ${{ matrix.dotnet }} build
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build
        run: dotnet pack -c Release --include-symbols -p:PackageVersion=$(date +"%Y.%m.%d") ".\HardwareInformation\HardwareInformation.csproj"
      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Nuget release
        if: startsWith(github.ref, 'refs/tags/')
        run: nuget SetApiKey ${{ secrets.NUGET_API_KEY }} && nuget push HardwareInformation/HardwareInformation/bin/Release/HardwareInformation.$(date +"%Y.%m.%d").nupkg -source https://nuget.smbsrc.net/
      - name: Release
        uses: docker://softprops/action-gh-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: HardwareInformation/HardwareInformation/bin/Release/**/*
          name: $(date +"%Y.%m.%d")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
