name: .NET Core CI

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        dotnet: [ '3.0.100-preview8-013656' ]
    name: Dotnet ${{ matrix.dotnet }} build
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: echo $(date "+%Y.%-m.%-d") > ./version
      - name: Build
        run: dotnet pack -c Release --include-symbols -p:PackageVersion=$(cat ./version) --output nupkgs "./HardwareInformation.sln"
