  
name: .NET Core CI

on: 
  push:
    branches: 
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet build and push
    steps:
      - uses: actions/checkout@v1
      - run: echo $(date "+%Y.%-m.%-d") > ./version
      - run: echo ${{ github.ref }} > ./version && sed -ie 's/refs\/tags\///' ./version
        if: startsWith(github.ref, 'refs/tags/')
      - name: Build
        run: dotnet pack -c Release --include-symbols -p:PackageVersion=$(cat ./version) --output nupkgs "./HardwareInformation.sln"
      - name: Nuget release
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push nupkgs/HardwareInformation.$(cat ./version).nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        
      - name: GPR-Hack
        if: startsWith(github.ref, 'refs/tags/')
        run: |
           for f in ./nupkgs/*.nupkg
           do
             curl -vX PUT -u "L3tum:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/L3tum/
           done
      - uses: actions/setup-node@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Setup node package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir package
          cd HardwareInformation/Scripts
          cp -r ./* ../../package/
          cd ..
          cp package.template.json ../package/package.json
          cd ../package
          npm version --no-git-tag-version $(cat ../version)
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        run: |
          cd package 
          npm publish --access public
        if: startsWith(github.ref, 'refs/tags/')
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@l3tum'
        if: startsWith(github.ref, 'refs/tags/')
      - name: Publish to GPR
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          cd package 
          npm publish --access public
        if: startsWith(github.ref, 'refs/tags/')
