  
name: .NET Core CI

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        dotnet: [ '3.0.100' ]
    name: Dotnet ${{ matrix.dotnet }} build
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: echo $(date "+%Y.%-m.%-d") > ./version
      - run: echo ${{ github.ref }} > ./version && sed -ie 's/refs\/tags\///' ./version
        if: startsWith(github.ref, 'refs/tags/')
      - name: Build
        run: dotnet pack -c Release --include-symbols -p:PackageVersion=$(cat ./version) --output nupkgs "./HardwareInformation.sln"
      - name: Nuget release
        if: startsWith(github.ref, 'refs/tags/')
        run: dotnet nuget push nupkgs/HardwareInformation.$(cat ./version).nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

      - name: Setup nuget config
        run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' .nuget.config > nuget.config
      - name: Publish nuget
        run: dotnet nuget push nupkgs/HardwareInformation.$(cat ./version).nupkg -s "github"
