name: .NET Core Simple Test

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macOS-latest]
        dotnet: [ '3.1.x', '5.0.0-rc.2' ]
    name: Dotnet ${{ matrix.dotnet }} build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build
        run: dotnet build -c Debug
      - name: Test
        run: dotnet SimpleGatheringTest/bin/Debug/netcoreapp3.0/SimpleGatheringTest.dll
