name: .NET Core CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        dotnet: [ '3.0.100-preview8-013656' ]
        version: [ '1.0.0']
    name: Dotnet ${{ matrix.dotnet }} build for version ${{ version }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet pack -c Release --include-symbols -p:PackageVersion=${{ version }} HardwareInformation/HardwareInformation.csproj
      - name: Deploy NuGet Package
        uses: anuraj/nuget-push@v0.2-Alpha
        with:
          nugetpackage: HardwareInformation/HardwareInformation/bin/Release/HardwareInformation.${{ version }}.nupkg
          nugetapikey: ${{ secrets.NUGET_API_KEY }}
