name: .NET Core Simple Test

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        dotnet: [ '3.0.100' ]
    name: Dotnet ${{ matrix.dotnet }} build
    steps:
      - uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet SimpleGatheringTest/bin/Release/netcoreapp3.0/SimpleGatheringTest.dll
